bugfix/partitions.csv / partitions-ota.csv/nvs issues
Wrong partition label for nvs in partitions.csv / partirions-ota.csv files. Label was vs instead of nvs. This caused CORRUPT HEAP: multi_heap.c:415 errors when using Lua NVS module.